### ISSUE TITLE
Apply page

### ISSUE THREAD

**Issue by buddhima-coforma** [coforma/swift-tech-challenge#33]
### Description
Setup a page with a form that students can use to apply to college

### User Story
As prospective student, once I have identified college(s) that fit me, I want to know what's needed to apply to that college and also be able to apply to it

### Acceptance Criteria

- [ ] Student can enter all of the following
  - [ ] First name
  - [ ] Last name
  - [ ] Email address
      - [ ] With basic email validation
  - [ ] Phone number
      - [ ] With 10-digit validation
  - [ ] SAT scores (for Math, Critical reading, Writing) 	
      - [ ] With validation for integers 200-800
      - [ ] SAT scores are only required (with little star) for schools
      - [ ] If SAT = No SAT score required, text under question header appears “[school] does not require the SAT. You are welcome to submit them anyway.
            - [ ] THIS ISN’T IN THE MOCKUP!
  - [ ] Essay Question 1 (same for all colleges)
  - [ ] Essay Questions 2+3 (diff for each college)
- [ ] Student can submit the form
  - [ ] there is a sticky "bottom bar" at the bottom of the page with a Submit button and a Close button

### Tasks and Constraints
1. A user arrive at this page when they select 'apply' on a given college tile or details page
2. Show fields relevant to that college, with relevant context
3. Simple validation for fields to prevent inaccurate entry (where applicable) - SAT fields are integers, essay question has a word count
4. Required fields are indicated. They change based on school.
5. If the user has started entering data and tries to navigate away, warn them that they will lose data

### Resources
See figma for finalized designs. in the page called "Ready".
![Image](https://github.com/coforma/swift-tech-challenge/assets/122126772/5db706e6-3aab-4c8f-beaa-f679f071ff45)

### Definition of Done
[Definition of Done](https://github.com/coforma/swift-tech-challenge/blob/main/documentation/product/definition_of_done.md)

**Comment by skylerschain** [comment]
Mocks [here](https://www.figma.com/file/SGP8E3EDGxhN3vE4N74zWZ/Swift-Tech-Challenge?type=design&node-id=248-62762&mode=dev).
